services:
  wasm-benchmark:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: wasm-benchmark
    user: "1000:1000"
    working_dir: /app

    # Volume mounts for persistent data and development
    volumes:
      - .:/app
      - ./results:/app/results
      - ./reports:/app/reports
      - ./builds:/app/builds

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'

    # Environment variables
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - PYTHONUNBUFFERED=1
      - RUST_BACKTRACE=1

    # Keep container running for exec commands
    command: tail -f /dev/null

    # Health check
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s