services:
  wasm-benchmark:
    image: alleninnz/wasm-benchmark:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: wasm-benchmark
    working_dir: /app

    # Volume mounts for persistent data and development
    volumes:
      - ./results:/app/results
      - ./reports:/app/reports
      - ./builds:/app/builds

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "1.0"

    # Environment variables (browser config inherited from Dockerfile)
    environment:
      - PYTHONUNBUFFERED=1
      - RUST_BACKTRACE=1
      - CHROME_ARGS=--headless --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222

    # Keep container running for exec commands
    command: tail -f /dev/null

    # Health check (uses Dockerfile HEALTHCHECK)
