# Engineering-Grade WebAssembly Benchmark Configuration
# Simplified for engineering reliability, not academic rigor
# Focus: Practical Rust vs TinyGo performance comparison for engineering decisions

experiment:
  name: "Rust vs TinyGo WebAssembly Performance Comparison"
  version: "2.1"
  description: "Engineering-focused performance comparison for language selection decisions"

# Simplified measurement parameters for engineering reliability
environment:
  warmup_runs: 15
  measure_runs: 50
  repetitions: 2

  # Basic timeout strategy
  timeout_ms: 90000           # Standard 90s timeout for all tasks

# Simplified task definitions - keep core scales only
tasks:
  mandelbrot:
    description: "CPU-intensive computation test"
    scales:
      small:
        width: 256
        height: 256
        max_iter: 500
      medium:
        width: 512
        height: 512
        max_iter: 1000
      large:
        width: 1024
        height: 1024
        max_iter: 2000
    fixed_params:
      center_real: -0.743643887037
      center_imag: 0.131825904205
      scale_factor: 3.0

  json_parse:
    description: "Object allocation and parsing test"
    scales:
      small:
        record_count: 5000
      medium:
        record_count: 15000
      large:
        record_count: 45000
    schema:
      fields: ["id", "value", "flag", "name"]
      id_sequential: true
      value_random: true
      flag_derived: true
      name_pattern: "user_{id}"

  matrix_mul:
    description: "Dense matrix multiplication test"
    scales:
      small:
        dimension: 256
      medium:
        dimension: 384
      large:
        dimension: 512
    computation:
      data_type: "f32"
      algorithm: "naive_triple_loop"
      precision_digits: 6

# Simplified language configurations
languages:
  rust:
    enabled: true
    target: "wasm32-unknown-unknown"
    optimization_levels:
      - name: "optimized"
        cargo_flags: "--release"
        cargo_config:
          opt_level: 3
          lto: "fat"
          codegen_units: 1
          panic: "abort"
          strip: "debuginfo"
    post_processing:
      - "wasm-strip"
      - "wasm-opt -O3"

  tinygo:
    enabled: true
    target: "wasm"
    optimization_levels:
      - name: "optimized"
        build_flags:
          - "-opt=3"
          - "-panic=trap"
          - "-no-debug"
          - "-scheduler=none"
    post_processing:
      - "wasm-strip"
      - "wasm-opt -Oz"

# Basic verification
verification:
  hash_algorithm: "fnv1a"
  hash_offset_basis: 2166136261
  hash_prime: 16777619
  floating_point_precision: 6

# Engineering-focused quality control
qc:
  max_coefficient_variation: 0.15
  outlier_iqr_multiplier: 1.5
  min_valid_samples: 30

  # timeout handling
  timeout_handling:
    treat_timeout_as: "failure"     # Timeouts are failures, not data
    max_timeout_rate: 0.1          # 10% timeout rate maximum

# Engineering-focused statistical analysis
statistics:
  confidence_level: 0.95           # Standard 95% confidence
  significance_alpha: 0.05         # Standard Î± = 0.05
  effect_size_metric: "cohens_d"   # Cohen's d for effect size

  effect_size_thresholds:
    small: 0.3
    medium: 0.6
    large: 1.0
  minimum_detectable_effect: 0.3

# Visualization and plotting configuration
plots:
  # Output settings
  dpi_basic: 150                   # DPI for basic comparison charts
  dpi_detailed: 300                # DPI for detailed analysis charts
  format: "png"                    # Output file format

  # Styling configuration
  figure_size_basic: [10, 6]       # Figure size for basic charts [width, height]
  figure_size_detailed: [16, 12]   # Figure size for detailed charts [width, height]

  # Font configuration
  font_size_default: 11            # Default font size
  font_size_labels: 12             # Axis and label font size
  font_size_titles: 14             # Title font size

  # Color scheme for languages
  color_scheme:
    rust: "#CE422B"                # Rust orange-red
    tinygo: "#00ADD8"              # Go cyan-blue


